//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub discord_id: String,
    #[sea_orm(unique)]
    pub minecraft_uuid: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::oauth_tokens::Entity")]
    OauthTokens,
}

impl Related<super::oauth_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
